// <auto-generated />
namespace Data_Access_Layer__DAL_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202107112129091_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
